### ISSUE TITLE
[Update 1.21.50] Existing Pack TO-DO

### ISSUE THREAD

**Issue by SquatchHunter** [BedrockTweaks/Files#414]
**NEW BLOCK** Pale Oak Leaves
- [x] Nicer Fast Leaves
- [x] #417 

**NEW BLOCK** Pale Oak Logs
- [x] Circular Log Tops
- [x] More Bark (#431)

**NEW BLOCK** Pale Oak Planks
- [x] Variated Planks
- [x] Old Planks
- [x] Back to Blocks (#431)
- [x] More Trapdoors (#431)
- [x] More Stairs (#431)

**NEW BLOCK** Resin Block
- [x] Back to Blocks (#431)
- [x] Double Slabs (#431)

**NEW BLOCK** Pale Moss
- [x] #419 

**NEW ENTITY** Creaking
- [x] #413 

**PACK PARITY**
- [x] #411 
- [x] #412 (if possible)
- [x] #416 

**PACK UPDATES**
- [x] Brighter Nether
- [x] Black Nether Bricks
- [x] Add Mangrove Leaves to Nicer Faster Leaves
- [x] Grass Sides & Lower Grass

**Comment by PAPISOP** [comment]
I think there are more packs that need to be updated with new wood type

**Comment by PAPISOP** [comment]
also need to update the crafting tweaks to include the new wood type

**Comment by NSPC911** [comment]
> - [ ] Trial Chamber Panorama
#415 + #416
